import {InternalEObject} from "../ecore/InternalEObject";
import {ConferencePackageLiterals} from "../conference/ConferencePackageLiterals";
import {ENotificationImpl} from "../ecore/ENotificationImpl";
import {NotificationImpl} from "../ecore/NotificationImpl";
import {BasicEObjectImpl} from "../ecore/BasicEObjectImpl";
import {EClass} from "../ecore/EClass";
import {NotificationChain} from "../ecore/NotificationChain";
//import ENotificationImpl = Ecore.ENotificationImpl;
//import EClass = Ecore.EClass;
